services:
  kafka:
    platform: linux/arm64
    image: &kafka-image apache/kafka:latest
    ports:
      - "9092:9092"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh kafka-topics.sh --bootstrap-server localhost:9092 --list" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s

  init-kafka:
    platform: linux/arm64
    image: *kafka-image
    working_dir: /opt/kafka/bin
    entrypoint: /bin/bash
    command: |
      kafka-topics.sh --create --if-not-exists --topic halan --bootstrap-server kafka:9092
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy

  bff:
    platform: linux/arm64
    build:
      context: .
      dockerfile: bf-todo/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      service-todo:
        condition: service_started
      service-payment:
        condition: service_started

  service-payment:
    platform: linux/arm64
    build:
      context: .
      dockerfile: service-payment/Dockerfile

    ports:
      - "9001:9001"
    env_file:
      - .env
    depends_on:
      init-kafka:
        condition: service_completed_successfully
  service-todo:
    platform: linux/arm64
    build:
      context: .
      dockerfile: service-todo/Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      init-kafka:
        condition: service_completed_successfully
