services:
  bff:
    platform: linux/arm64
    build:
      context: .
      dockerfile: bf-todo/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway" 
  service-payment:
    platform: linux/arm64
    build:
      context: .
      dockerfile: service-payment/Dockerfile
    ports:
      - "9001:9001"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  service-todo:
    platform: linux/arm64
    build:
      context: .
      dockerfile: service-todo/Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
