// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: todo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertTodoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertTodoReq) Reset() {
	*x = InsertTodoReq{}
	mi := &file_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertTodoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertTodoReq) ProtoMessage() {}

func (x *InsertTodoReq) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertTodoReq.ProtoReflect.Descriptor instead.
func (*InsertTodoReq) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{0}
}

func (x *InsertTodoReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type InsertTodoRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertTodoRes) Reset() {
	*x = InsertTodoRes{}
	mi := &file_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertTodoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertTodoRes) ProtoMessage() {}

func (x *InsertTodoRes) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertTodoRes.ProtoReflect.Descriptor instead.
func (*InsertTodoRes) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{1}
}

func (x *InsertTodoRes) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type DeleteTodoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=ObjectId,proto3" json:"ObjectId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoReq) Reset() {
	*x = DeleteTodoReq{}
	mi := &file_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoReq) ProtoMessage() {}

func (x *DeleteTodoReq) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoReq.ProtoReflect.Descriptor instead.
func (*DeleteTodoReq) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteTodoReq) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type DeleteTodoRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoRes) Reset() {
	*x = DeleteTodoRes{}
	mi := &file_todo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoRes) ProtoMessage() {}

func (x *DeleteTodoRes) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoRes.ProtoReflect.Descriptor instead.
func (*DeleteTodoRes) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{3}
}

type GetTodoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=ObjectId,proto3" json:"ObjectId,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,2,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodoReq) Reset() {
	*x = GetTodoReq{}
	mi := &file_todo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoReq) ProtoMessage() {}

func (x *GetTodoReq) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoReq.ProtoReflect.Descriptor instead.
func (*GetTodoReq) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{4}
}

func (x *GetTodoReq) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetTodoReq) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type GetTodoRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=ObjectId,proto3" json:"ObjectId,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,3,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodoRes) Reset() {
	*x = GetTodoRes{}
	mi := &file_todo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoRes) ProtoMessage() {}

func (x *GetTodoRes) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoRes.ProtoReflect.Descriptor instead.
func (*GetTodoRes) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{5}
}

func (x *GetTodoRes) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetTodoRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTodoRes) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type GetTodosReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodosReq) Reset() {
	*x = GetTodosReq{}
	mi := &file_todo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodosReq) ProtoMessage() {}

func (x *GetTodosReq) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodosReq.ProtoReflect.Descriptor instead.
func (*GetTodosReq) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{6}
}

type GetTodosRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todos         []*GetTodoRes          `protobuf:"bytes,1,rep,name=Todos,proto3" json:"Todos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodosRes) Reset() {
	*x = GetTodosRes{}
	mi := &file_todo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodosRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodosRes) ProtoMessage() {}

func (x *GetTodosRes) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodosRes.ProtoReflect.Descriptor instead.
func (*GetTodosRes) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{7}
}

func (x *GetTodosRes) GetTodos() []*GetTodoRes {
	if x != nil {
		return x.Todos
	}
	return nil
}

type DepositReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float32                `protobuf:"fixed32,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositReq) Reset() {
	*x = DepositReq{}
	mi := &file_todo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositReq) ProtoMessage() {}

func (x *DepositReq) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositReq.ProtoReflect.Descriptor instead.
func (*DepositReq) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{8}
}

func (x *DepositReq) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DepositRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositRes) Reset() {
	*x = DepositRes{}
	mi := &file_todo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRes) ProtoMessage() {}

func (x *DepositRes) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRes.ProtoReflect.Descriptor instead.
func (*DepositRes) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{9}
}

func (x *DepositRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DepositRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WithdrawReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float32                `protobuf:"fixed32,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawReq) Reset() {
	*x = WithdrawReq{}
	mi := &file_todo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawReq) ProtoMessage() {}

func (x *WithdrawReq) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawReq.ProtoReflect.Descriptor instead.
func (*WithdrawReq) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{10}
}

func (x *WithdrawReq) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type WithdrawRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawRes) Reset() {
	*x = WithdrawRes{}
	mi := &file_todo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawRes) ProtoMessage() {}

func (x *WithdrawRes) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawRes.ProtoReflect.Descriptor instead.
func (*WithdrawRes) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{11}
}

func (x *WithdrawRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WithdrawRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TransferReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float32                `protobuf:"fixed32,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=To,proto3" json:"To,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferReq) Reset() {
	*x = TransferReq{}
	mi := &file_todo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferReq) ProtoMessage() {}

func (x *TransferReq) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferReq.ProtoReflect.Descriptor instead.
func (*TransferReq) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{12}
}

func (x *TransferReq) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferReq) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type TransferRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRes) Reset() {
	*x = TransferRes{}
	mi := &file_todo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRes) ProtoMessage() {}

func (x *TransferRes) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRes.ProtoReflect.Descriptor instead.
func (*TransferRes) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{13}
}

func (x *TransferRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TransferRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_todo_proto protoreflect.FileDescriptor

const file_todo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"todo.proto\x12\x05proto\"#\n" +
	"\rInsertTodoReq\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\tR\x04Data\"#\n" +
	"\rInsertTodoRes\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\tR\x04Data\"+\n" +
	"\rDeleteTodoReq\x12\x1a\n" +
	"\bObjectId\x18\x01 \x01(\tR\bObjectId\"\x0f\n" +
	"\rDeleteTodoRes\"F\n" +
	"\n" +
	"GetTodoReq\x12\x1a\n" +
	"\bObjectId\x18\x01 \x01(\tR\bObjectId\x12\x1c\n" +
	"\tCreatedBy\x18\x02 \x01(\tR\tCreatedBy\"`\n" +
	"\n" +
	"GetTodoRes\x12\x1a\n" +
	"\bObjectId\x18\x01 \x01(\tR\bObjectId\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\x12\x1c\n" +
	"\tCreatedBy\x18\x03 \x01(\tR\tCreatedBy\"\r\n" +
	"\vGetTodosReq\"6\n" +
	"\vGetTodosRes\x12'\n" +
	"\x05Todos\x18\x01 \x03(\v2\x11.proto.GetTodoResR\x05Todos\"$\n" +
	"\n" +
	"DepositReq\x12\x16\n" +
	"\x06Amount\x18\x01 \x01(\x02R\x06Amount\">\n" +
	"\n" +
	"DepositRes\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\x05R\x06Status\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\"%\n" +
	"\vWithdrawReq\x12\x16\n" +
	"\x06Amount\x18\x01 \x01(\x02R\x06Amount\"?\n" +
	"\vWithdrawRes\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\x05R\x06Status\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\"5\n" +
	"\vTransferReq\x12\x16\n" +
	"\x06Amount\x18\x01 \x01(\x02R\x06Amount\x12\x0e\n" +
	"\x02To\x18\x02 \x01(\tR\x02To\"?\n" +
	"\vTransferRes\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\x05R\x06Status\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage2\x8d\x03\n" +
	"\vTodoService\x12:\n" +
	"\n" +
	"InsertTodo\x12\x14.proto.InsertTodoReq\x1a\x14.proto.InsertTodoRes\"\x00\x12:\n" +
	"\n" +
	"DeleteTodo\x12\x14.proto.DeleteTodoReq\x1a\x14.proto.DeleteTodoRes\"\x00\x121\n" +
	"\aGetTodo\x12\x11.proto.GetTodoReq\x1a\x11.proto.GetTodoRes\"\x00\x124\n" +
	"\bGetTodos\x12\x12.proto.GetTodosReq\x1a\x12.proto.GetTodosRes\"\x00\x121\n" +
	"\aDeposit\x12\x11.proto.DepositReq\x1a\x11.proto.DepositRes\"\x00\x124\n" +
	"\bWithdraw\x12\x12.proto.WithdrawReq\x1a\x12.proto.WithdrawRes\"\x00\x124\n" +
	"\bTransfer\x12\x12.proto.TransferReq\x1a\x12.proto.TransferRes\"\x00B\tZ\a/;protob\x06proto3"

var (
	file_todo_proto_rawDescOnce sync.Once
	file_todo_proto_rawDescData []byte
)

func file_todo_proto_rawDescGZIP() []byte {
	file_todo_proto_rawDescOnce.Do(func() {
		file_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_todo_proto_rawDesc), len(file_todo_proto_rawDesc)))
	})
	return file_todo_proto_rawDescData
}

var file_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_todo_proto_goTypes = []any{
	(*InsertTodoReq)(nil), // 0: proto.InsertTodoReq
	(*InsertTodoRes)(nil), // 1: proto.InsertTodoRes
	(*DeleteTodoReq)(nil), // 2: proto.DeleteTodoReq
	(*DeleteTodoRes)(nil), // 3: proto.DeleteTodoRes
	(*GetTodoReq)(nil),    // 4: proto.GetTodoReq
	(*GetTodoRes)(nil),    // 5: proto.GetTodoRes
	(*GetTodosReq)(nil),   // 6: proto.GetTodosReq
	(*GetTodosRes)(nil),   // 7: proto.GetTodosRes
	(*DepositReq)(nil),    // 8: proto.DepositReq
	(*DepositRes)(nil),    // 9: proto.DepositRes
	(*WithdrawReq)(nil),   // 10: proto.WithdrawReq
	(*WithdrawRes)(nil),   // 11: proto.WithdrawRes
	(*TransferReq)(nil),   // 12: proto.TransferReq
	(*TransferRes)(nil),   // 13: proto.TransferRes
}
var file_todo_proto_depIdxs = []int32{
	5,  // 0: proto.GetTodosRes.Todos:type_name -> proto.GetTodoRes
	0,  // 1: proto.TodoService.InsertTodo:input_type -> proto.InsertTodoReq
	2,  // 2: proto.TodoService.DeleteTodo:input_type -> proto.DeleteTodoReq
	4,  // 3: proto.TodoService.GetTodo:input_type -> proto.GetTodoReq
	6,  // 4: proto.TodoService.GetTodos:input_type -> proto.GetTodosReq
	8,  // 5: proto.TodoService.Deposit:input_type -> proto.DepositReq
	10, // 6: proto.TodoService.Withdraw:input_type -> proto.WithdrawReq
	12, // 7: proto.TodoService.Transfer:input_type -> proto.TransferReq
	1,  // 8: proto.TodoService.InsertTodo:output_type -> proto.InsertTodoRes
	3,  // 9: proto.TodoService.DeleteTodo:output_type -> proto.DeleteTodoRes
	5,  // 10: proto.TodoService.GetTodo:output_type -> proto.GetTodoRes
	7,  // 11: proto.TodoService.GetTodos:output_type -> proto.GetTodosRes
	9,  // 12: proto.TodoService.Deposit:output_type -> proto.DepositRes
	11, // 13: proto.TodoService.Withdraw:output_type -> proto.WithdrawRes
	13, // 14: proto.TodoService.Transfer:output_type -> proto.TransferRes
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_todo_proto_init() }
func file_todo_proto_init() {
	if File_todo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todo_proto_rawDesc), len(file_todo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todo_proto_goTypes,
		DependencyIndexes: file_todo_proto_depIdxs,
		MessageInfos:      file_todo_proto_msgTypes,
	}.Build()
	File_todo_proto = out.File
	file_todo_proto_goTypes = nil
	file_todo_proto_depIdxs = nil
}
