// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: todo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TodoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
	ObjectId      *string                `protobuf:"bytes,2,opt,name=ObjectId,proto3,oneof" json:"ObjectId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoReq) Reset() {
	*x = TodoReq{}
	mi := &file_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoReq) ProtoMessage() {}

func (x *TodoReq) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoReq.ProtoReflect.Descriptor instead.
func (*TodoReq) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{0}
}

func (x *TodoReq) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *TodoReq) GetObjectId() string {
	if x != nil && x.ObjectId != nil {
		return *x.ObjectId
	}
	return ""
}

type TodoRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      *string                `protobuf:"bytes,1,opt,name=ObjectId,proto3,oneof" json:"ObjectId,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoRes) Reset() {
	*x = TodoRes{}
	mi := &file_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoRes) ProtoMessage() {}

func (x *TodoRes) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoRes.ProtoReflect.Descriptor instead.
func (*TodoRes) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{1}
}

func (x *TodoRes) GetObjectId() string {
	if x != nil && x.ObjectId != nil {
		return *x.ObjectId
	}
	return ""
}

func (x *TodoRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Todos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todos         []*TodoRes             `protobuf:"bytes,1,rep,name=Todos,proto3" json:"Todos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todos) Reset() {
	*x = Todos{}
	mi := &file_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todos) ProtoMessage() {}

func (x *Todos) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todos.ProtoReflect.Descriptor instead.
func (*Todos) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{2}
}

func (x *Todos) GetTodos() []*TodoRes {
	if x != nil {
		return x.Todos
	}
	return nil
}

var File_todo_proto protoreflect.FileDescriptor

const file_todo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"todo.proto\x12\x05proto\"K\n" +
	"\aTodoReq\x12\x12\n" +
	"\x04Body\x18\x01 \x01(\tR\x04Body\x12\x1f\n" +
	"\bObjectId\x18\x02 \x01(\tH\x00R\bObjectId\x88\x01\x01B\v\n" +
	"\t_ObjectId\"Q\n" +
	"\aTodoRes\x12\x1f\n" +
	"\bObjectId\x18\x01 \x01(\tH\x00R\bObjectId\x88\x01\x01\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessageB\v\n" +
	"\t_ObjectId\"-\n" +
	"\x05Todos\x12$\n" +
	"\x05Todos\x18\x01 \x03(\v2\x0e.proto.TodoResR\x05Todos2\x9b\x01\n" +
	"\vTodoService\x12.\n" +
	"\n" +
	"InsertTodo\x12\x0e.proto.TodoReq\x1a\x0e.proto.TodoRes\"\x00\x12.\n" +
	"\n" +
	"DeleteTodo\x12\x0e.proto.TodoReq\x1a\x0e.proto.TodoRes\"\x00\x12,\n" +
	"\n" +
	"SelectTodo\x12\x0e.proto.TodoReq\x1a\f.proto.Todos\"\x00B\tZ\a/;protob\x06proto3"

var (
	file_todo_proto_rawDescOnce sync.Once
	file_todo_proto_rawDescData []byte
)

func file_todo_proto_rawDescGZIP() []byte {
	file_todo_proto_rawDescOnce.Do(func() {
		file_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_todo_proto_rawDesc), len(file_todo_proto_rawDesc)))
	})
	return file_todo_proto_rawDescData
}

var file_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_todo_proto_goTypes = []any{
	(*TodoReq)(nil), // 0: proto.TodoReq
	(*TodoRes)(nil), // 1: proto.TodoRes
	(*Todos)(nil),   // 2: proto.Todos
}
var file_todo_proto_depIdxs = []int32{
	1, // 0: proto.Todos.Todos:type_name -> proto.TodoRes
	0, // 1: proto.TodoService.InsertTodo:input_type -> proto.TodoReq
	0, // 2: proto.TodoService.DeleteTodo:input_type -> proto.TodoReq
	0, // 3: proto.TodoService.SelectTodo:input_type -> proto.TodoReq
	1, // 4: proto.TodoService.InsertTodo:output_type -> proto.TodoRes
	1, // 5: proto.TodoService.DeleteTodo:output_type -> proto.TodoRes
	2, // 6: proto.TodoService.SelectTodo:output_type -> proto.Todos
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_todo_proto_init() }
func file_todo_proto_init() {
	if File_todo_proto != nil {
		return
	}
	file_todo_proto_msgTypes[0].OneofWrappers = []any{}
	file_todo_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todo_proto_rawDesc), len(file_todo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todo_proto_goTypes,
		DependencyIndexes: file_todo_proto_depIdxs,
		MessageInfos:      file_todo_proto_msgTypes,
	}.Build()
	File_todo_proto = out.File
	file_todo_proto_goTypes = nil
	file_todo_proto_depIdxs = nil
}
